Telephony: Fix translation compile error
* Languages that require specifying the format specifier more than once
  (e.g. because they need "few", "many", "other") fail to compile:
  error: multiple substitutions specified in non-positional format;
  did you mean to add the formatted="false" attribute?
* These languages are missing translations currently and are commented
  with "format error in translation for ..."
* By giving the original string a positional format, the substitution
  can be used more than once and thus also be applies to the other
  languages
* In order to keep the existing translations working, these were also
  modified

Change-Id: I4de88fd63a58cf25d90aa478823d5ee629bbdd41