Set min_sdk_version: "31" on aosp_test_rcsclient
Previously, a bug in the generation of `api_versions_*` modules that
excluded non-public SDK extension APIs was preventing the
`ConnectivityManager.registerQosCallback(...)` method from being
included with the correct information about the SDK extension versions
in which it was added. When that bug is fixed it changes the
`api_versions_system` as follows:
```
- <method name="registerQosCallback(Landroid/net/QosSocketInfo;Ljava/util/concurrent/Executor;Landroid/net/QosCallback;)V" since="31"/>
+ <method name="registerQosCallback(Landroid/net/QosSocketInfo;Ljava/util/concurrent/Executor;Landroid/net/QosCallback;)V" since="31" sdks="34:1,0:31"/>
```

That causes Android lint to report the following problem:
```
packages/services/Telephony/testapps/TestRcsApp/aosp_test_rcsclient/src/com/android/libraries/rcs/simpleclient/protocol/msrp/MsrpSession.java:118: Error: Call requires version 1 of the U Extensions SDK (current min is 0): android.net.ConnectivityManager#registerQosCallback [NewApi]
            connectivityManager.registerQosCallback(new QosSocketInfo(network, socket),
```

This change fixes that issue by changing the `min_sdk_version` from
`30` to `31` on `aosp_test_rcs_client_base` and `TestRcsApp`.

See `errorpone-trunk-staging:git_main` result on Patchset2 of
https://r.android.com/3061686.

Bug: 336993217
Test: ABTD errorprone test
Change-Id: I80b281ca2d533cc59a734af00ea7c9bc81c06886